name: Copy A File
description: copying a File

inputs:
    filename: 
        required: true
        description: filename to Copy
    sourcePath:
        required: true
        description: source location
    targetLocation:
        required: true
        description: target location
        
runs:
   using: "composite"
   steps:
    - name: Copy File
      run: |
        mkdir "/data/sourcePath"
        mkdir "/data/targetLocation"
        echo "test_1.log" > /data/sourcePath/test.log
        echo "test_2.log" > /data/sourcePath/test2.txt
        echo "test_3.log" > /data/sourcePath/test.logtxt
        echo "test_4.log" > /data/sourcePath/test.txtlog
        echo "test_5.log" > /data/sourcePath/test.log2
        echo "test_6.log" > /data/sourcePath/test.log3
    - name: Check if file was created
      run: |
          if ${{ github.events.inputs.filename }} ; then 
          echo "File Exists"
          exit 1
          else
            echo "File didn't exist" 
      shell: bash
       
        