name: Copy A File
description: copying a File

inputs:
    filename: 
        required: true
        description: filename to Copy
    sourcePath:
        required: true
        description: source location
    targetLocation:
        required: true
        description: target location
        
runs:
   using: "composite"
   steps:
    - name: Copy File
      run: |
        mkdir -p ${{ inputs.sourcePath }}
        mkdir -p ${{ inputs.targetLocation }}
        echo "test_1.log" > ${{ inputs.sourcePath }}/test.log
        echo "test_2.log" > ${{ inputs.sourcePath }}/test2.txt
        echo "test_3.log" > ${{ inputs.sourcePath }}/test.logtxt
        echo "test_4.log" > ${{ inputs.sourcePath }}/test.txtlog
        echo "test_5.log" > ${{ inputs.sourcePath }}/test.log2
        echo "test_6.log" > ${{ inputs.sourcePath }}/test.log3
      shell: bash

    - name: Copy A File
      run: |
          if [[ -f ${{ env.given_source_path}}/${{ env.given_file_name }} ]]; then
              cp -rf ${{ env.given_source_path }}/${{ env.given_file_name }} ${{ env.given_target_Location }}/${{ env.given_file_name }} 
              echo "Successfully copied"
          else
            echo "${{ env.given_file_name }} File Not Exists"
            exit 1
          fi
      env:
        given_file_name : ${{ inputs.filename }}  
        given_source_path : ${{ inputs.sourcePath }}
        given_target_Location : ${{ inputs.targetLocation }} 
      shell: bash
       
        
