# This is a basic workflow to help you get started with Actions

name: Custom env var

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:    
  Day_of_week: Funday
  testvar: value-1

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  mainjob:  
    name: 'print the env vars'
    runs-on: ubuntu-latest

    env:
      Greeting: Dear
      testvar: value-2
 # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: print-value-of-env-var

      run: |
         echo "$Greeting $First_Name. Today is $Day_of_week!"
         echo "testvar $testvar"
         echo "testvar ${{ env.testvar }}"
      env:
         First_Name: Student
         testvar: value-3  
      shell: bash
      
