name: List of all default github vars

on:
   workflow_dispatch:


jobs:
  ubuntu-environment-variables:
    runs-on: ubuntu-latest
    steps: 
      - run: env
      
  windods-environment-variables:
    runs-on: windows-latest
    steps: 
      - run: env

  macos-environment-variables:
    runs-on: windows-latest
    steps: 
      - run: env   
      
      

