name: finding a preexisting file

on:
  workflow_dispatch:

jobs:
    job_1: 
        name: 'create some files'
        runs-on: ubuntu-latest
        steps:
            - name: create files
              run: |
                mkdir "/home/philips/Test"
                mkdir "/home/philips/Test_Target"
                echo "test-log" > /home/philips/Test/test.log
                echo "test-log" > /home/philips/Test/test2.txt
                echo "test-log" > /home/philips/Test/test.logtxt
                echo "test-log" > /home/philips/Test/test.txtlog
                echo "test-log" > /home/philips/Test/test.log2
                echo "test-log" > /home/philips/Test/test.log3
   
    job_1: 
        name: 'finding and downloading the file'
        runs-on: ubuntu-latest
        steps:
            - uses: ./.github/actions/Copy 
        with:
            filename: action 
            sourcepath: /home/philips/Test
            targetpath: /home/philips/Test_Target

  job_2:
   name: 'Download file present or not'
   runs-on: ubuntu-latest
   needs: job_1  
   steps:
    - uses: actions/download-Copy
      with: 
        name: action
    -  run: cat action.yml



