name: Octo Organization CI

on:
    workflow_dispatch:
        inputs:
            filename: 
                description: "Provide_file_name"
                required: True
                default:      
            sourcePath:
                description: "Provide_Source_Path"
                required: True
                default: "C:\\Data\\Github_Actions"
            targetLocation:
                description: "Provide_target_Location"
                required: True
                default: "C:\\Data\\ActionCreation"
jobs:
  build:
    runs-on: windows-latest
    

    steps:
      - name: Checkout_latest_CODE
        uses: action/checkout@v3
        with:
          filename: ${{ github.events.inputs.filename }}
          sourcePath: ${{ github.events.inputs.sourcePath }} 
          targetLocation: ${{ github.events.inputs.targetLocation }}
          
      - uses: ./.github/actions/Copy/action.yml
          

   