name: Octo Organization CI

on:
    workflow_dispatch:
        inputs:
            filename: 
                description: "Provide_Build_Number"
                required: True
                default: "2022.11.036"
            sourcePath:
                description: "Provide_Build_Number"
                required: True
                default: "C:\Data\Github_Actions"
            targetLocation:
                description: "Provide_Build_Number"
                required: True
                default: "C:\Data\ActionCreation"
jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: ./.github/actions/Copy
        with:
          filename: ${{ github.events.inputs.filename }}
          sourcePath: ${{ github.events.inputs.sourcePath }} 
          targetLocation: ${{ github.events.inputs.targetLocation }}
          
       
          

   