name: Octo Organization CI

on:
    workflow_dispatch:
        inputs:
            filename: 
                description: "Provide_file_name"
                required: True
                default:      
            sourcePath:
                description: "Provide_Source_Path"
                required: True
                default: "$HOME/source_path"
            targetLocation:
                description: "Provide_target_Location"
                required: True
                default: "$HOME/target_path"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: copysomefiles
        uses: Kanishka1425/Github_Actions/.github/actions/Copy@main
        with:
          filename: ${{ github.event.inputs.filename }}
          sourcePath: ${{ github.event.inputs.sourcePath }} 
          targetLocation: ${{ github.event.inputs.targetLocation }}
          

   
