name: Octo Organization CI

on:
    workflow_dispatch:
        inputs:
            filename: 
                description: "Provide_file_name"
                required: True
                default:      
            sourcePath:
                description: "Provide_Source_Path"
                required: True
                default: "C:\\Data\\Github_Actions"
            targetLocation:
                description: "Provide_target_Location"
                required: True
                default: "C:\\Data\\ActionCreation"
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: copysomefiles
        uses: Kanishka1425/Github_Actions/.github/workflows/action.yml@main
        with:
          filename: ${{ github.event.inputs.filename }}
          sourcePath: ${{ github.event.inputs.sourcePath }} 
          targetLocation: ${{ github.event.inputs.targetLocation }}
          

   