name: 'use_of_Env var' 

on: workflow_dispatch

jobs: 
  use_of_Env_var: 
    runs-on: ubuntu-latest
    steps: 
    - name: set_the_value
      id: step_one
      run: |
       echo "action_state=yellow" >> $use_of_Env
    - name: use the value
      id: step_two
      run: |
       echo "${{env.action_state}}" # this will output yellow